### ISSUE TITLE
api-web-app

### ISSUE THREAD

**Issue by Leboroz** [Leboroz/api-web-app#21]
**This is a 2 people project.**

<a href="https://github.com/Leboroz/api-web-app">Link to project.</a>

**Comment by omar-labana** [comment]
Hi <STUDENT_MENTION>, 

Excellent work so far! 👌
You have added all the required cards. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [x] Kindly make sure that all of the cards are assigned to a team member(5 cards left).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
